export const INITIALIZE = 'INITIALIZE';

export const UPDATE_CORE_INFO = 'UPDATE_CORE_INFO';
export const UPDATE_THEME = 'UPDATE_THEME';

export const SET_USER_ACCOUNTS = 'SET_USER_ACCOUNTS';
export const SET_ACCOUNT_TRANSACTIONS = 'SET_ACCOUNT_TRANSACTIONS';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const ADD_TRANSACTION_DATAPACKET = 'ADD_TRANSACTION_DATAPACKET';
export const ADD_TIMESTAMP_DATAPACKET = 'ADD_TIMESTAMP_DATAPACKET';

export const SET_GATHERING_INFO = 'SET_GATHERING_INFO';

export const SET_FROM_QUERY = 'SET_FROM_QUERY';
export const SET_TO_QUERY = 'SET_TO_QUERY';
export const SET_TIMESPAN = 'SET_TIMESPAN';
export const SET_OPERATION = 'SET_OPERATION';
